# 01 - Data Understanding

Review raw schema, initial quality checks, and business context.

In [2]:
import pandas as pd
from pathlib import Path

print('Data understanding notebook')

Data understanding notebook

In [3]:
customers = pd.read_excel("../data/raw/Senior_Data_Scientist_Assessment_Data (1) (1) (1) (1).xlsx", sheet_name="Customers")
departments = pd.read_excel("../data/raw/Senior_Data_Scientist_Assessment_Data (1) (1) (1) (1).xlsx", sheet_name="Departments")
users = pd.read_excel("../data/raw/Senior_Data_Scientist_Assessment_Data (1) (1) (1) (1).xlsx", sheet_name="Users")
products = pd.read_excel("../data/raw/Senior_Data_Scientist_Assessment_Data (1) (1) (1) (1).xlsx", sheet_name="Products")
leads = pd.read_excel("../data/raw/Senior_Data_Scientist_Assessment_Data (1) (1) (1) (1).xlsx", sheet_name="Leads")
installations = pd.read_excel("../data/raw/Senior_Data_Scientist_Assessment_Data (1) (1) (1) (1).xlsx", sheet_name="Installations")
accounts = pd.read_excel("../data/raw/Senior_Data_Scientist_Assessment_Data (1) (1) (1) (1).xlsx", sheet_name="Accounts")
sales = pd.read_excel("../data/raw/Senior_Data_Scientist_Assessment_Data (1) (1) (1) (1).xlsx", sheet_name="Sales")

In [92]:
customers.head()

,id,region,Gender,Location,Date_of_birth,Latitude,Longitude,created_at,updated_at
0,CUST-10000,uganda,Female,Jinja,1983-10-22,2.949384,42.616604,2022-01-18,2022-11-16
1,CUST-10001,uganda,Female,Kampala,1978-05-25,4.580776,46.412738,2023-06-25,2024-01-13
2,CUST-10002,civ,Male,Abidjan,1974-06-05,-1.344683,44.132175,2023-02-19,2024-05-19
3,CUST-10003,kenya,Male,Mombasa,1989-03-31,-0.155258,36.244213,2022-10-02,2024-06-12
4,CUST-10004,kenya,Male,Nairobi,1989-07-05,-1.266943,42.295066,2023-07-04,2023-11-01

In [13]:
users.head()

      Id            Name departmentId  created_at  updated_at
0  U1000       Mary Moyo         D104  2023-03-29  2023-07-24
1  U1001      David Kone         D104  2022-06-07  2022-08-09
2  U1002       Mary Ouma         D101  2022-04-27  2022-09-16
3  U1003     Sarah Koffi         D100  2023-03-10  2023-09-23
4  U1004  Moses Ssentamu         D103  2022-12-02  2023-03-23

In [14]:
products.head()

     Id                Product  is_refurb  created_at  updated_at
0  P200  Solar Home System 10W       True  2021-02-07  2024-02-10
1  P201  Solar Home System 20W       True  2021-06-04  2023-12-29
2  P202        Clean Cookstove       True  2021-11-02  2022-01-02
3  P203             Smartphone      False  2021-03-24  2021-08-31
4  P204               Solar TV      False  2021-03-22  2022-10-09

In [15]:
leads.head()

           Id          Source customer_id  created_at  updated_at
0  LEAD-50000        Roadshow  CUST-10000  2023-04-14  2023-04-20
1  LEAD-50001  Refer and Earn  CUST-10001  2023-03-19  2023-09-30
2  LEAD-50002        Facebook  CUST-10002  2022-06-27  2023-03-06
3  LEAD-50003        Facebook  CUST-10003  2022-03-31  2023-12-31
4  LEAD-50004         Website  CUST-10004  2023-11-20  2023-12-15

In [16]:
installations.head()

           Id Installation_date engineer_id  created_at  updated_at
0  INST-70000        2022-12-24       U1012  2022-12-24  2023-10-10
1  INST-70001        2022-01-08       U1026  2022-01-08  2024-02-27
2  INST-70002        2023-06-08       U1012  2023-06-08  2024-01-20
3  INST-70003        2023-06-18       U1025  2023-06-18  2023-07-18
4  INST-70004        2023-01-10       U1002  2023-01-10  2023-05-04

In [17]:
accounts.head()

,id,customer_id,status,type,created_at,updated_at,Installation_id,Dispatch_date,First_installment_date,Agent_id,Proudct_id,lead_id
0,ACC-90000,CUST-10000,Arrears,PAYG,2023-07-24,2024-02-22,INST-70000,2023-07-24,2023-08-10,U1008,P203,LEAD-50000
1,ACC-90001,CUST-10001,Complete,CASH,2023-07-30,2024-06-28,INST-70001,2023-07-30,2023-08-13,U1003,P206,LEAD-50001
2,ACC-90002,CUST-10002,Repossession,PAYG,2022-02-17,2022-10-01,INST-70002,2022-02-17,2022-03-05,U1011,P203,LEAD-50002
3,ACC-90003,CUST-10003,Repossed,PAYG,2022-07-23,2024-01-03,INST-70003,2022-07-23,2022-07-27,U1008,P206,LEAD-50003
4,ACC-90004,CUST-10004,Refunded,PAYG,2023-12-13,2024-03-27,INST-70004,2023-12-13,2024-01-01,U1014,P205,LEAD-50004

In [18]:
sales.head()

            Id account_id   Sale_date  created_at  updated_at
0  SALE-100000  ACC-90000  2023-07-24  2023-07-24  2023-12-30
1  SALE-100001  ACC-90001  2023-07-30  2023-07-30  2024-03-25
2  SALE-100002  ACC-90002  2022-02-17  2022-02-17  2023-07-06
3  SALE-100003  ACC-90003  2022-07-23  2022-07-23  2024-02-23
4  SALE-100004  ACC-90004  2023-12-13  2023-12-13  2024-01-03

In [11]:
leads.describe()

                Id    Source customer_id  created_at  updated_at
count         6000      6000        5000        6000        6000
unique        6000         8        5000         821         792
top     LEAD-50000  Roadshow  CUST-10000  2022-03-10  2024-04-21
freq             1       796           1          17          27

In [ ]:
leads.loc[~ (leads['Id'].isin(accounts['lead_id']))]

              Id          Source customer_id  created_at  updated_at
4750  LEAD-54750         Walk-in  CUST-14750  2022-10-26  2024-02-10
4751  LEAD-54751  Refer and Earn  CUST-14751  2023-07-30  2024-02-13
4752  LEAD-54752  Refer and Earn  CUST-14752  2022-09-14  2024-01-12
4753  LEAD-54753    Door to Door  CUST-14753  2023-09-06  2024-02-02
4754  LEAD-54754        Partners  CUST-14754  2022-05-21  2023-05-22
...          ...             ...         ...         ...         ...
5995  LEAD-55995        Partners         NaN  2023-06-22  2023-10-14
5996  LEAD-55996       Telesales         NaN  2023-05-11  2023-06-10
5997  LEAD-55997        Facebook         NaN  2023-01-06  2023-09-20
5998  LEAD-55998         Walk-in         NaN  2022-09-14  2023-04-02
5999  LEAD-55999    Door to Door         NaN  2022-03-05  2023-11-28

[1250 rows x 5 columns]

# Prepare data for fact and dimension tables for quick analytics

In [13]:
from clickhouse_driver import Client
from datetime import datetime, timedelta
client = Client(
    host="localhost",
    port=9000,
    user="clickhouse_user",
    password="clickhouse_password"
)

print(client.execute("SELECT version()"))

[('25.12.1.649',)]

### Populating the dim_country AND dim_location table

dim_country
(
    country_id  UUID DEFAULT generateUUIDv4(),
    country_name String,
    currency String
)

dim_location
(
    location_id UUID DEFAULT generateUUIDv4(),
    country_id UUID,
    location_name String
)

#### Step 1: Determine the Countries from the Customers data

In [39]:
customers.head()

,id,region,Gender,Location,Date_of_birth,Latitude,Longitude,created_at,updated_at
0,CUST-10000,uganda,Female,Jinja,1983-10-22,2.949384,42.616604,2022-01-18,2022-11-16
1,CUST-10001,uganda,Female,Kampala,1978-05-25,4.580776,46.412738,2023-06-25,2024-01-13
2,CUST-10002,civ,Male,Abidjan,1974-06-05,-1.344683,44.132175,2023-02-19,2024-05-19
3,CUST-10003,kenya,Male,Mombasa,1989-03-31,-0.155258,36.244213,2022-10-02,2024-06-12
4,CUST-10004,kenya,Male,Nairobi,1989-07-05,-1.266943,42.295066,2023-07-04,2023-11-01

In [ ]:
countries = customers['region'].unique()
dim_countries_df = pd.DataFrame({"country_name": countries, "currency": ["USh", "KSh", "CFA Franc"], "region_cluster": ["East Africa", "East Africa", "West Africa"]})
dim_countries_df.head()

In [51]:
for index, row in dim_countries_df.iterrows():
    client.execute(
        "INSERT INTO sunculture_db.dim_country (country_name, currency) VALUES",
        [(row['country_name'], row['currency'])]
    )

In [53]:
client.execute("SELECT * FROM sunculture_db.dim_country LIMIT 5", with_column_types=True)

([(UUID('352d617d-673d-4173-9c03-051d840103e0'), 'uganda', 'USh'),
  (UUID('b94de882-caef-44d8-b7f5-1cd7c293d491'), 'civ', 'KSh'),
  (UUID('85bda175-cce8-43e0-a002-b0f799e0bac3'), 'kenya', 'CFA Franc')],
 [('country_id', 'UUID'), ('country_name', 'String'), ('currency', 'String')])

In [54]:
dim_countries_df = pd.DataFrame(client.execute("SELECT * FROM sunculture_db.dim_country", with_column_types=True)[0], columns=[col[0] for col in client.execute("SELECT * FROM sunculture_db.dim_country", with_column_types=True)[1]])
dim_countries_df.head()

                             country_id country_name   currency
0  352d617d-673d-4173-9c03-051d840103e0       uganda        USh
1  85bda175-cce8-43e0-a002-b0f799e0bac3        kenya  CFA Franc
2  b94de882-caef-44d8-b7f5-1cd7c293d491          civ        KSh

In [75]:
country_locations_data = pd.DataFrame(customers[['region','Location']].value_counts()).reset_index()
dim_location_df = pd.merge(dim_countries_df, country_locations_data, left_on='country_name', right_on='region', how='outer')[['country_id', 'country_name', 'Location']]
dim_location_df = dim_location_df.rename(columns={'Location': 'location_name'})
dim_location_df

                             country_id country_name location_name
0  b94de882-caef-44d8-b7f5-1cd7c293d491          civ  Yamoussoukro
1  b94de882-caef-44d8-b7f5-1cd7c293d491          civ        Bouaké
2  b94de882-caef-44d8-b7f5-1cd7c293d491          civ       Abidjan
3  85bda175-cce8-43e0-a002-b0f799e0bac3        kenya       Mombasa
4  85bda175-cce8-43e0-a002-b0f799e0bac3        kenya        Kisumu
5  85bda175-cce8-43e0-a002-b0f799e0bac3        kenya       Nairobi
6  352d617d-673d-4173-9c03-051d840103e0       uganda         Jinja
7  352d617d-673d-4173-9c03-051d840103e0       uganda       Entebbe
8  352d617d-673d-4173-9c03-051d840103e0       uganda       Kampala

In [76]:
for index, row in dim_location_df.iterrows():
    client.execute(
        "INSERT INTO sunculture_db.dim_location (location_name, country_id) VALUES",
        [(row['location_name'], row['country_id'])]
    )

In [118]:
dim_location_df = pd.DataFrame(client.execute("SELECT * FROM sunculture_db.dim_location", with_column_types=True)[0], columns=[col[0] for col in client.execute("SELECT * FROM sunculture_db.dim_location", with_column_types=True)[1]])
dim_location_df

,location_id,country_id,location_name
0,1268ab4b-af1b-4685-ba1f-08daed9df23f,b94de882-caef-44d8-b7f5-1cd7c293d491,Yamoussoukro
1,a6d43822-ca41-479d-aa48-aa158762c809,b94de882-caef-44d8-b7f5-1cd7c293d491,Bouaké
2,f942620a-e675-4839-86c6-f3bbc9f42a3d,b94de882-caef-44d8-b7f5-1cd7c293d491,Abidjan
3,450273c9-5f9f-419c-b90f-8b92bd1a4fcc,85bda175-cce8-43e0-a002-b0f799e0bac3,Mombasa
4,6101e06a-c73e-4ac0-b68a-46715ab250e7,85bda175-cce8-43e0-a002-b0f799e0bac3,Kisumu
5,a11b3f36-9a7b-453c-aa86-e632af528b61,85bda175-cce8-43e0-a002-b0f799e0bac3,Nairobi
6,0c91ce94-e47a-4524-8c2e-99dd20bd4604,352d617d-673d-4173-9c03-051d840103e0,Jinja
7,ba7ad696-602c-4c55-9d83-0df79c5366a0,352d617d-673d-4173-9c03-051d840103e0,Entebbe
8,1be0d0fd-22b0-4598-9fa9-a08ba11f549c,352d617d-673d-4173-9c03-051d840103e0,Kampala

### Populating the dim_customer table

dim_customer
(
    customer_id String,
    first_name String,
    last_name String,
    gender String,
    date_of_birth Date,
    age UInt8,
    age_bucket String,
    phone_number String,
    country_id UInt32,
    city String,
    created_at DateTime
)

In [95]:
client.execute("SELECT * FROM sunculture_db.dim_customer LIMIT 5", with_column_types=True)

([],
 [('customer_id', 'String'),
  ('gender', 'String'),
  ('date_of_birth', 'Date'),
  ('age', 'UInt8'),
  ('age_bucket', 'String'),
  ('country_id', 'UInt32'),
  ('city', 'String'),
  ('created_at', 'DateTime'),
  ('latitude', 'Float32'),
  ('longitude', 'Float32')])

In [119]:
dim_customers_df = customers.copy()

In [120]:
dim_customers_df['Date_of_birth'] = pd.to_datetime(dim_customers_df['Date_of_birth'], errors='coerce')
dim_customers_df['Age'] = dim_customers_df['Date_of_birth'].apply(lambda x: datetime.now().year - x.year)

In [121]:
dim_customers_df['age_bucket'] = pd.cut(dim_customers_df['Age'], bins=[0, 18, 35, 50, 100], labels=['0-18', '19-35', '36-50', '51+'])

In [122]:
dim_customers_df['created_at'] = pd.to_datetime(dim_customers_df['created_at'], errors='coerce')

In [123]:
dim_location_df

,location_id,country_id,location_name
0,1268ab4b-af1b-4685-ba1f-08daed9df23f,b94de882-caef-44d8-b7f5-1cd7c293d491,Yamoussoukro
1,a6d43822-ca41-479d-aa48-aa158762c809,b94de882-caef-44d8-b7f5-1cd7c293d491,Bouaké
2,f942620a-e675-4839-86c6-f3bbc9f42a3d,b94de882-caef-44d8-b7f5-1cd7c293d491,Abidjan
3,450273c9-5f9f-419c-b90f-8b92bd1a4fcc,85bda175-cce8-43e0-a002-b0f799e0bac3,Mombasa
4,6101e06a-c73e-4ac0-b68a-46715ab250e7,85bda175-cce8-43e0-a002-b0f799e0bac3,Kisumu
5,a11b3f36-9a7b-453c-aa86-e632af528b61,85bda175-cce8-43e0-a002-b0f799e0bac3,Nairobi
6,0c91ce94-e47a-4524-8c2e-99dd20bd4604,352d617d-673d-4173-9c03-051d840103e0,Jinja
7,ba7ad696-602c-4c55-9d83-0df79c5366a0,352d617d-673d-4173-9c03-051d840103e0,Entebbe
8,1be0d0fd-22b0-4598-9fa9-a08ba11f549c,352d617d-673d-4173-9c03-051d840103e0,Kampala

In [124]:
dim_customers_df = pd.merge(dim_customers_df, dim_countries_df, left_on='region', right_on='country_name', how='left')

In [125]:
dim_customers_df = pd.merge(dim_customers_df, dim_location_df, left_on=['country_id','Location'], right_on=['country_id','location_name'], how='left')

In [203]:
dim_customers_df.columns

Index(['id', 'region', 'Gender', 'Location', 'Date_of_birth', 'Latitude',
       'Longitude', 'created_at', 'updated_at', 'Age', 'age_bucket',
       'country_id', 'country_name', 'currency', 'location_id',
       'location_name'],
      dtype='object')

In [132]:
for index, row in dim_customers_df.iterrows():
    client.execute(
        "INSERT INTO sunculture_db.dim_customer (customer_id, gender, date_of_birth, age, age_bucket, country_id, location_id, latitude, longitude, created_at) VALUES",
        [(row['id'], row['Gender'], row['Date_of_birth'], row['Age'], row['age_bucket'], row['country_id'], row['location_id'], row['Latitude'], row['Longitude'], row['created_at'])]
    )

### Populating the dim_products table

dim_product
(
    product_id UInt64,
    product_name String,
    refurb_status String,
    created_at DateTime
)

In [136]:
dim_product_df = products.copy()
dim_product_df['created_at'] = pd.to_datetime(dim_product_df['created_at'], errors='coerce')
dim_product_df = dim_product_df.rename(columns={'Id': 'product_id', 'Product': 'product_name', 'is_refurb': 'refurb_status'})

In [138]:
for index, row in dim_product_df.iterrows():
    client.execute(
        "INSERT INTO sunculture_db.dim_product (product_id, product_name, refurb_status, created_at) VALUES",
        [(row['product_id'], row['product_name'], row['refurb_status'], row['created_at'])]
    )

### Populating the dim_lead_source table

dim_lead_source
(
    lead_source_id UUID DEFAULT generateUUIDv4(),
    lead_source_name String
)

In [145]:
dim_lead_source_df = leads.copy()

In [146]:
lead_sources = dim_lead_source_df.Source.unique()
dim_lead_source_df = pd.DataFrame({"lead_source_name": lead_sources})

In [151]:
dim_lead_source_df['lead_source_name']

0          Roadshow
1    Refer and Earn
2          Facebook
3           Website
4           Walk-in
5         Telesales
6          Partners
7      Door to Door
Name: lead_source_name, dtype: object

In [ ]:
for lead_source in dim_lead_source_df['lead_source_name'].tolist():
    print(lead_source)
    client.execute(
        f"INSERT INTO sunculture_db.dim_lead_source (lead_source_name) VALUES ('{lead_source}');"
    )

Roadshow
Refer and Earn
Facebook
Website
Walk-in
Telesales
Partners
Door to Door

### Populating the dim_employee and dim_departments table

dim_employee
(
    user_id String,
    full_name String,
    department_id String,
    created_at DateTime
)

dim_department
(
    department_id String,
    department_name String
)

In [158]:
dim_employee_df = users.copy()
dim_department_df = departments.copy()

In [164]:
dim_employee_df['created_at'] = pd.to_datetime(dim_employee_df['created_at'], errors='coerce')

In [ ]:
for index, row in dim_department_df.iterrows():
    client.execute(
        "INSERT INTO sunculture_db.dim_department (department_id, department_name) VALUES",
        [(row['Id'], row['name'])]
    )

ServerException: Code: 60.
DB::Exception: Table sunculture_db.dim_employee does not exist. Maybe you meant default.dim_employee?. Stack trace:

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x00000000163a0f6a
1. DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000de0034e
2. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000ddffd40
3. DB::Exception::Exception<String, String, String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type>, String&&, String&&, String&&, String&&) @ 0x000000000df103f6
4. DB::IDatabase::getTable(String const&, std::shared_ptr<DB::Context const>) const @ 0x000000001a43df3d
5. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, std::shared_ptr<DB::Context const>, std::optional<DB::Exception>*) const @ 0x000000001b165ccb
6. DB::DatabaseCatalog::getTable(DB::StorageID const&, std::shared_ptr<DB::Context const>) const @ 0x000000001b16e449
7. DB::InterpreterInsertQuery::getTable(DB::ASTInsertQuery&) @ 0x000000001b2cde23
8. DB::InterpreterInsertQuery::execute() @ 0x000000001b2d4af5
9. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>, std::function<void ()>, DB::QueryResultDetails&) @ 0x000000001b751f84
10. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x000000001b74c490
11. DB::TCPHandler::runImpl() @ 0x000000001cf83be8
12. DB::TCPHandler::run() @ 0x000000001cfa5f24
13. Poco::Net::TCPServerConnection::start() @ 0x00000000223ba5c7
14. Poco::Net::TCPServerDispatcher::run() @ 0x00000000223baab1
15. Poco::PooledThread::run() @ 0x000000002237a71c
16. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000022378bcf
17. ? @ 0x0000000000094ac3
18. ? @ 0x00000000001268c0

In [165]:
for index, row in dim_employee_df.iterrows():
    client.execute(
        "INSERT INTO sunculture_db.dim_employee (employee_id, full_name, department_id, created_at) VALUES",
        [(row['Id'], row['Name'], row['departmentId'], row['created_at'])]
    )

### Populating the dim_account_status table

dim_account_status
(
    account_status_id  UUID DEFAULT generateUUIDv4(),
    account_status_name String,
    risk_category String
)

In [168]:
dim_account_status_df = accounts.copy()
account_statuses = dim_account_status_df['status'].unique()

# account statuses: array(['Arrears', 'Complete', 'Repossession', 'Repossed', 'Refunded',
#       'Write Off', 'No Deposit', 'Advance'], dtype=object)

dim_account_status_df = pd.DataFrame({"account_status_name": account_statuses, "risk_category": ["High Risk", "Low Risk", "High Risk", "High Risk", "Low Risk", "High Risk", "Low Risk", "Low Risk"]})

In [169]:
dim_account_status_df

  account_status_name risk_category
0             Arrears     High Risk
1            Complete      Low Risk
2        Repossession     High Risk
3            Repossed     High Risk
4            Refunded      Low Risk
5           Write Off     High Risk
6          No Deposit      Low Risk
7             Advance      Low Risk

In [172]:
for index, row in dim_account_status_df.iterrows():
    client.execute(
        "INSERT INTO sunculture_db.dim_account_status (account_status_name, risk_category) VALUES",
        [(row['account_status_name'], row['risk_category'])]
    )

### Populating the fact_sales table

fact_sales
(
    sale_id String,
    customer_id String,
    product_id String,
    lead_source_id UUID,
    employee_id String,
    account_id String,
    country_id UUID,
    sale_date Date,
    sale_timestamp DateTime,
    account_type String,
    account_status String,
    created_at DateTime
)

In [175]:
fact_sales_df = sales.copy()
fact_accounts_df = accounts.copy()
fact_installations_df = installations.copy()
fact_leads_df = leads.copy()

In [177]:
fact_sales_df = fact_sales_df.rename(columns={'Id': 'sale_id','Sale_date': 'sale_date', })

In [178]:
fact_sales_df

          sale_id account_id   sale_date  created_at  updated_at
0     SALE-100000  ACC-90000  2023-07-24  2023-07-24  2023-12-30
1     SALE-100001  ACC-90001  2023-07-30  2023-07-30  2024-03-25
2     SALE-100002  ACC-90002  2022-02-17  2022-02-17  2023-07-06
3     SALE-100003  ACC-90003  2022-07-23  2022-07-23  2024-02-23
4     SALE-100004  ACC-90004  2023-12-13  2023-12-13  2024-01-03
...           ...        ...         ...         ...         ...
4745  SALE-104745  ACC-94745  2022-09-18  2022-09-18  2022-11-24
4746  SALE-104746  ACC-94746  2022-12-11  2022-12-11  2023-05-21
4747  SALE-104747  ACC-94747  2023-11-21  2023-11-21  2024-03-06
4748  SALE-104748  ACC-94748  2022-12-14  2022-12-14  2023-12-19
4749  SALE-104749  ACC-94749  2023-11-11  2023-11-11  2024-04-26

[4750 rows x 5 columns]

In [186]:
fact_accounts_df = fact_accounts_df.rename(columns={'id': 'account_id', 'status': 'account_status', 'type': 'account_type', 'Installation_id':'installation_id','Agent_id':'employee_id', 'Proudct_id':'product_id'})

In [187]:
fact_accounts_df

,account_id,customer_id,account_status,account_type,created_at,updated_at,installation_id,Dispatch_date,First_installment_date,employee_id,product_id,lead_id
0,ACC-90000,CUST-10000,Arrears,PAYG,2023-07-24,2024-02-22,INST-70000,2023-07-24,2023-08-10,U1008,P203,LEAD-50000
1,ACC-90001,CUST-10001,Complete,CASH,2023-07-30,2024-06-28,INST-70001,2023-07-30,2023-08-13,U1003,P206,LEAD-50001
2,ACC-90002,CUST-10002,Repossession,PAYG,2022-02-17,2022-10-01,INST-70002,2022-02-17,2022-03-05,U1011,P203,LEAD-50002
3,ACC-90003,CUST-10003,Repossed,PAYG,2022-07-23,2024-01-03,INST-70003,2022-07-23,2022-07-27,U1008,P206,LEAD-50003
4,ACC-90004,CUST-10004,Refunded,PAYG,2023-12-13,2024-03-27,INST-70004,2023-12-13,2024-01-01,U1014,P205,LEAD-50004
...,...,...,...,...,...,...,...,...,...,...,...,...
4745,ACC-94745,CUST-14745,Arrears,PAYG,2022-09-18,2024-04-10,NaN,2022-09-18,2022-09-23,U1014,P204,LEAD-54745
4746,ACC-94746,CUST-14746,Refunded,PAYG,2022-12-11,2023-11-02,NaN,2022-12-11,2022-12-15,U1016,P209,LEAD-54746
4747,ACC-94747,CUST-14747,Arrears,CASH,2023-11-21,2024-03-23,NaN,2023-11-21,2023-12-12,U1003,P205,LEAD-54747
4748,ACC-94748,CUST-14748,No Deposit,PAYG,2022-12-14,2022-12-21,NaN,2022-12-14,2022-12-21,U1008,P209,LEAD-54748
4749,ACC-94749,CUST-14749,Advance,PAYG,2023-11-11,2024-04-25,NaN,2023-11-11,2023-11-28,U1003,P201,LEAD-54749

In [188]:
fact_sales_df = pd.merge(fact_sales_df, fact_accounts_df[['account_id','customer_id','account_status','account_type','installation_id','employee_id','product_id','lead_id']], left_on='account_id', right_on='account_id', how='left')

In [196]:
leads

              Id          Source customer_id  created_at  updated_at
0     LEAD-50000        Roadshow  CUST-10000  2023-04-14  2023-04-20
1     LEAD-50001  Refer and Earn  CUST-10001  2023-03-19  2023-09-30
2     LEAD-50002        Facebook  CUST-10002  2022-06-27  2023-03-06
3     LEAD-50003        Facebook  CUST-10003  2022-03-31  2023-12-31
4     LEAD-50004         Website  CUST-10004  2023-11-20  2023-12-15
...          ...             ...         ...         ...         ...
5995  LEAD-55995        Partners         NaN  2023-06-22  2023-10-14
5996  LEAD-55996       Telesales         NaN  2023-05-11  2023-06-10
5997  LEAD-55997        Facebook         NaN  2023-01-06  2023-09-20
5998  LEAD-55998         Walk-in         NaN  2022-09-14  2023-04-02
5999  LEAD-55999    Door to Door         NaN  2022-03-05  2023-11-28

[6000 rows x 5 columns]

In [197]:
fact_sales_df = pd.merge(fact_sales_df, leads[['Id','Source']], left_on='lead_id', right_on='Id', how='left')

In [198]:
fact_sales_df

,sale_id,account_id,sale_date,created_at,updated_at,customer_id,account_status,account_type,installation_id,employee_id,product_id,lead_id,Id,Source
0,SALE-100000,ACC-90000,2023-07-24,2023-07-24,2023-12-30,CUST-10000,Arrears,PAYG,INST-70000,U1008,P203,LEAD-50000,LEAD-50000,Roadshow
1,SALE-100001,ACC-90001,2023-07-30,2023-07-30,2024-03-25,CUST-10001,Complete,CASH,INST-70001,U1003,P206,LEAD-50001,LEAD-50001,Refer and Earn
2,SALE-100002,ACC-90002,2022-02-17,2022-02-17,2023-07-06,CUST-10002,Repossession,PAYG,INST-70002,U1011,P203,LEAD-50002,LEAD-50002,Facebook
3,SALE-100003,ACC-90003,2022-07-23,2022-07-23,2024-02-23,CUST-10003,Repossed,PAYG,INST-70003,U1008,P206,LEAD-50003,LEAD-50003,Facebook
4,SALE-100004,ACC-90004,2023-12-13,2023-12-13,2024-01-03,CUST-10004,Refunded,PAYG,INST-70004,U1014,P205,LEAD-50004,LEAD-50004,Website
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4745,SALE-104745,ACC-94745,2022-09-18,2022-09-18,2022-11-24,CUST-14745,Arrears,PAYG,NaN,U1014,P204,LEAD-54745,LEAD-54745,Walk-in
4746,SALE-104746,ACC-94746,2022-12-11,2022-12-11,2023-05-21,CUST-14746,Refunded,PAYG,NaN,U1016,P209,LEAD-54746,LEAD-54746,Refer and Earn
4747,SALE-104747,ACC-94747,2023-11-21,2023-11-21,2024-03-06,CUST-14747,Arrears,CASH,NaN,U1003,P205,LEAD-54747,LEAD-54747,Walk-in
4748,SALE-104748,ACC-94748,2022-12-14,2022-12-14,2023-12-19,CUST-14748,No Deposit,PAYG,NaN,U1008,P209,LEAD-54748,LEAD-54748,Refer and Earn
4749,SALE-104749,ACC-94749,2023-11-11,2023-11-11,2024-04-26,CUST-14749,Advance,PAYG,NaN,U1003,P201,LEAD-54749,LEAD-54749,Telesales

In [194]:
dim_lead_source_df = pd.DataFrame(client.execute("SELECT * FROM sunculture_db.dim_lead_source", with_column_types=True)[0], columns=[col[0] for col in client.execute("SELECT * FROM sunculture_db.dim_lead_source", with_column_types=True)[1]])

In [195]:
dim_lead_source_df

                         lead_source_id lead_source_name
0  0434709a-95ff-4f5f-847f-352e292dc355         Facebook
1  30f3c4db-628c-47d9-8a16-687a8962e0e1         Partners
2  0f16ec51-002f-4044-8f19-18befbfbfa33         Roadshow
3  d5fc05cb-b332-4898-905f-63a3840b4536   Refer and Earn
4  3417d4bf-677e-4ce0-9e02-56c3c10c5e2f          Walk-in
5  8530253e-a97b-4958-a303-88faaa4abee0          Website
6  3b82192a-856e-4535-a38a-2a5548d88f0c     Door to Door
7  bd66d773-fcee-4d34-b914-f258f458cb4c        Telesales

In [200]:
fact_sales_df = pd.merge(fact_sales_df, dim_lead_source_df, left_on='Source', right_on='lead_source_name',how='left')

In [201]:
fact_sales_df.columns

Index(['sale_id', 'account_id', 'sale_date', 'created_at', 'updated_at',
       'customer_id', 'account_status', 'account_type', 'installation_id',
       'employee_id', 'product_id', 'lead_id', 'Id', 'Source',
       'lead_source_id', 'lead_source_name'],
      dtype='object')

In [208]:
dim_customers_df.columns

Index(['id', 'region', 'Gender', 'Location', 'Date_of_birth', 'Latitude',
       'Longitude', 'created_at', 'updated_at', 'Age', 'age_bucket',
       'country_id', 'country_name', 'currency', 'location_id',
       'location_name'],
      dtype='object')

In [210]:
fact_sales_df = pd.merge(fact_sales_df, dim_customers_df[['id','country_id']], left_on='customer_id', right_on='id', how='left')

In [213]:
fact_sales_df['created_at'] = pd.to_datetime(fact_sales_df['created_at'], errors='coerce')
fact_sales_df['sale_date'] = pd.to_datetime(fact_sales_df['sale_date'], errors='coerce')

In [214]:
for index, row in fact_sales_df.iterrows():
    client.execute(
        "INSERT INTO sunculture_db.fact_sales (sale_id, account_id, customer_id, product_id, employee_id, lead_source_id, country_id, sale_date) VALUES",
        [(row['sale_id'], row['account_id'], row['customer_id'], row['product_id'], row['employee_id'], row['lead_source_id'], row['country_id'], row['sale_date'])]    
    )

In [243]:
fact_sales_df

,sale_id,account_id,sale_date,created_at,updated_at,customer_id,account_status,account_type,installation_id,employee_id,product_id,lead_id,Id,Source,lead_source_id,lead_source_name,id,country_id
0,SALE-100000,ACC-90000,2023-07-24,2023-07-24,2023-12-30,CUST-10000,Arrears,PAYG,INST-70000,U1008,P203,LEAD-50000,LEAD-50000,Roadshow,0f16ec51-002f-4044-8f19-18befbfbfa33,Roadshow,CUST-10000,352d617d-673d-4173-9c03-051d840103e0
1,SALE-100001,ACC-90001,2023-07-30,2023-07-30,2024-03-25,CUST-10001,Complete,CASH,INST-70001,U1003,P206,LEAD-50001,LEAD-50001,Refer and Earn,d5fc05cb-b332-4898-905f-63a3840b4536,Refer and Earn,CUST-10001,352d617d-673d-4173-9c03-051d840103e0
2,SALE-100002,ACC-90002,2022-02-17,2022-02-17,2023-07-06,CUST-10002,Repossession,PAYG,INST-70002,U1011,P203,LEAD-50002,LEAD-50002,Facebook,0434709a-95ff-4f5f-847f-352e292dc355,Facebook,CUST-10002,b94de882-caef-44d8-b7f5-1cd7c293d491
3,SALE-100003,ACC-90003,2022-07-23,2022-07-23,2024-02-23,CUST-10003,Repossed,PAYG,INST-70003,U1008,P206,LEAD-50003,LEAD-50003,Facebook,0434709a-95ff-4f5f-847f-352e292dc355,Facebook,CUST-10003,85bda175-cce8-43e0-a002-b0f799e0bac3
4,SALE-100004,ACC-90004,2023-12-13,2023-12-13,2024-01-03,CUST-10004,Refunded,PAYG,INST-70004,U1014,P205,LEAD-50004,LEAD-50004,Website,8530253e-a97b-4958-a303-88faaa4abee0,Website,CUST-10004,85bda175-cce8-43e0-a002-b0f799e0bac3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4745,SALE-104745,ACC-94745,2022-09-18,2022-09-18,2022-11-24,CUST-14745,Arrears,PAYG,NaN,U1014,P204,LEAD-54745,LEAD-54745,Walk-in,3417d4bf-677e-4ce0-9e02-56c3c10c5e2f,Walk-in,CUST-14745,b94de882-caef-44d8-b7f5-1cd7c293d491
4746,SALE-104746,ACC-94746,2022-12-11,2022-12-11,2023-05-21,CUST-14746,Refunded,PAYG,NaN,U1016,P209,LEAD-54746,LEAD-54746,Refer and Earn,d5fc05cb-b332-4898-905f-63a3840b4536,Refer and Earn,CUST-14746,352d617d-673d-4173-9c03-051d840103e0
4747,SALE-104747,ACC-94747,2023-11-21,2023-11-21,2024-03-06,CUST-14747,Arrears,CASH,NaN,U1003,P205,LEAD-54747,LEAD-54747,Walk-in,3417d4bf-677e-4ce0-9e02-56c3c10c5e2f,Walk-in,CUST-14747,352d617d-673d-4173-9c03-051d840103e0
4748,SALE-104748,ACC-94748,2022-12-14,2022-12-14,2023-12-19,CUST-14748,No Deposit,PAYG,NaN,U1008,P209,LEAD-54748,LEAD-54748,Refer and Earn,d5fc05cb-b332-4898-905f-63a3840b4536,Refer and Earn,CUST-14748,85bda175-cce8-43e0-a002-b0f799e0bac3
4749,SALE-104749,ACC-94749,2023-11-11,2023-11-11,2024-04-26,CUST-14749,Advance,PAYG,NaN,U1003,P201,LEAD-54749,LEAD-54749,Telesales,bd66d773-fcee-4d34-b914-f258f458cb4c,Telesales,CUST-14749,b94de882-caef-44d8-b7f5-1cd7c293d491

### Populate fact_accounts_snapshots table

```fact_accounts_snapshots
(
    account_id String,
    customer_id String,
    product_id String,
    country_id UUID,
    lead_source_id String,
    account_status_id UUID,
    activation_date Date,
    account_age_days UInt32,
    payment_type String,
    is_currently_in_arrears Boolean,
    created_at DateTime DEFAULT now()
)
```

In [227]:
accounts.Installation_id.info()

<class 'pandas.core.series.Series'>
RangeIndex: 4750 entries, 0 to 4749
Series name: Installation_id
Non-Null Count  Dtype
--------------  -----
4500 non-null   object
dtypes: object(1)
memory usage: 37.2+ KB

There are null values in the installation_id in 250 accounts which makes no sense since there is a dispatch_date and a  first_installment_date. This field also cannot be inferred. Perhaps this is a data entry error?

Also worth noting is that the installation_date in the Installation sheet is earlier than the dispatch_Date in the Accounts sheet which speaks to a data integrity error.

In [229]:
accounts.dropna(subset=['Installation_id'], inplace=True)

In [232]:
accounts.id.describe()

count          4500
unique         4500
top       ACC-90000
freq              1
Name: id, dtype: object

In [233]:
accounts.customer_id.describe()

count           4500
unique          4500
top       CUST-10000
freq               1
Name: customer_id, dtype: object

In [234]:
accounts.head()

,id,customer_id,status,type,created_at,updated_at,Installation_id,Dispatch_date,First_installment_date,Agent_id,Proudct_id,lead_id
0,ACC-90000,CUST-10000,Arrears,PAYG,2023-07-24,2024-02-22,INST-70000,2023-07-24,2023-08-10,U1008,P203,LEAD-50000
1,ACC-90001,CUST-10001,Complete,CASH,2023-07-30,2024-06-28,INST-70001,2023-07-30,2023-08-13,U1003,P206,LEAD-50001
2,ACC-90002,CUST-10002,Repossession,PAYG,2022-02-17,2022-10-01,INST-70002,2022-02-17,2022-03-05,U1011,P203,LEAD-50002
3,ACC-90003,CUST-10003,Repossed,PAYG,2022-07-23,2024-01-03,INST-70003,2022-07-23,2022-07-27,U1008,P206,LEAD-50003
4,ACC-90004,CUST-10004,Refunded,PAYG,2023-12-13,2024-03-27,INST-70004,2023-12-13,2024-01-01,U1014,P205,LEAD-50004

In [240]:
fact_accounts_snapshot_df = accounts.copy(deep=True)

In [241]:
fact_accounts_snapshot_df

,id,customer_id,status,type,created_at,updated_at,Installation_id,Dispatch_date,First_installment_date,Agent_id,Proudct_id,lead_id
0,ACC-90000,CUST-10000,Arrears,PAYG,2023-07-24,2024-02-22,INST-70000,2023-07-24,2023-08-10,U1008,P203,LEAD-50000
1,ACC-90001,CUST-10001,Complete,CASH,2023-07-30,2024-06-28,INST-70001,2023-07-30,2023-08-13,U1003,P206,LEAD-50001
2,ACC-90002,CUST-10002,Repossession,PAYG,2022-02-17,2022-10-01,INST-70002,2022-02-17,2022-03-05,U1011,P203,LEAD-50002
3,ACC-90003,CUST-10003,Repossed,PAYG,2022-07-23,2024-01-03,INST-70003,2022-07-23,2022-07-27,U1008,P206,LEAD-50003
4,ACC-90004,CUST-10004,Refunded,PAYG,2023-12-13,2024-03-27,INST-70004,2023-12-13,2024-01-01,U1014,P205,LEAD-50004
...,...,...,...,...,...,...,...,...,...,...,...,...
4495,ACC-94495,CUST-14495,Complete,PAYG,2022-09-28,2023-03-29,INST-74495,2022-09-28,2022-10-01,U1011,P205,LEAD-54495
4496,ACC-94496,CUST-14496,No Deposit,CASH,2023-11-20,2024-01-19,INST-74496,2023-11-20,2023-11-30,U1011,P205,LEAD-54496
4497,ACC-94497,CUST-14497,Arrears,PAYG,2023-04-16,2024-04-28,INST-74497,2023-04-16,2023-04-29,U1014,P207,LEAD-54497
4498,ACC-94498,CUST-14498,Advance,CASH,2022-08-29,2024-01-23,INST-74498,2022-08-29,2022-09-22,U1008,P204,LEAD-54498
4499,ACC-94499,CUST-14499,Refunded,CASH,2023-07-07,2023-10-09,INST-74499,2023-07-07,2023-07-15,U1017,P200,LEAD-54499

In [249]:
dim_account_status_df = pd.DataFrame(client.execute("SELECT * FROM sunculture_db.dim_account_status", with_column_types=True)[0], columns=[col[0] for col in client.execute("SELECT * FROM sunculture_db.dim_account_status", with_column_types=True)[1]])

In [250]:
dim_account_status_df

                      account_status_id account_status_name risk_category
0  1e277c75-34da-4859-8603-b0e16b0590e0             Arrears     High Risk
1  607f30f7-b97f-4998-8692-3013917a49f7        Repossession     High Risk
2  a3311867-48d9-4e96-8733-380654a52595             Advance      Low Risk
3  1b587c4d-422a-40d4-8858-9b3e6d5d89f3           Write Off     High Risk
4  f5abc6e7-d4ea-454d-a330-907652a0c601            Refunded      Low Risk
5  c7d10cc7-a0a1-4b48-afd4-1f3688b8e0aa            Complete      Low Risk
6  f772f358-b66e-4455-b077-80d1c301c4c5          No Deposit      Low Risk
7  f24861a8-e367-48f3-b5a1-f264a8b80d4c            Repossed     High Risk

In [ ]:
fact_accounts_snapshot_df=pd.merge(fact_accounts_snapshot_df, dim_customers_df.rename(columns={'id': 'customer_id'})[['customer_id', 'country_id']], left_on='customer_id', right_on='customer_id', how='left')
fact_accounts_snapshot_df = pd.merge(fact_accounts_snapshot_df,fact_sales_df[['lead_id', 'lead_source_name','lead_source_id']], left_on='lead_id', right_on='lead_id', how='left')
fact_accounts_snapshot_df = pd.merge(fact_accounts_snapshot_df, dim_account_status_df.rename(columns={'account_status_name': 'account_status'})[['account_status','account_status_id']], left_on='status', right_on='account_status', how='left')

In [264]:
fact_accounts_snapshot_df.created_at.info()

<class 'pandas.core.series.Series'>
RangeIndex: 4500 entries, 0 to 4499
Series name: created_at
Non-Null Count  Dtype
--------------  -----
4500 non-null   datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 35.3 KB

In [257]:
fact_accounts_snapshot_df.columns

Index(['id', 'customer_id', 'status', 'type', 'created_at', 'updated_at',
       'Installation_id', 'Dispatch_date', 'First_installment_date',
       'Agent_id', 'Proudct_id', 'lead_id', 'lead_source_name',
       'lead_source_id', 'account_status', 'account_status_id'],
      dtype='object')

In [258]:
fact_accounts_snapshot_df['created_at'] = pd.to_datetime(fact_accounts_snapshot_df['created_at'], errors='coerce')
fact_accounts_snapshot_df['Dispatch_date'] = pd.to_datetime(fact_accounts_snapshot_df['Dispatch_date'], errors='coerce')
fact_accounts_snapshot_df['First_installment_date'] = pd.to_datetime(fact_accounts_snapshot_df['First_installment_date'], errors='coerce')

In [284]:
(fact_accounts_snapshot_df['created_at'].max() - fact_accounts_snapshot_df['created_at'].min()).days

729

In [297]:
fact_accounts_snapshot_df.head(5)

,id,customer_id,status,type,created_at,updated_at,Installation_id,Dispatch_date,First_installment_date,Agent_id,Proudct_id,lead_id,lead_source_name,lead_source_id,account_status,account_status_id
0,ACC-90000,CUST-10000,Arrears,PAYG,2023-07-24,2024-02-22,INST-70000,2023-07-24,2023-08-10,U1008,P203,LEAD-50000,Roadshow,0f16ec51-002f-4044-8f19-18befbfbfa33,Arrears,1e277c75-34da-4859-8603-b0e16b0590e0
1,ACC-90001,CUST-10001,Complete,CASH,2023-07-30,2024-06-28,INST-70001,2023-07-30,2023-08-13,U1003,P206,LEAD-50001,Refer and Earn,d5fc05cb-b332-4898-905f-63a3840b4536,Complete,c7d10cc7-a0a1-4b48-afd4-1f3688b8e0aa
2,ACC-90002,CUST-10002,Repossession,PAYG,2022-02-17,2022-10-01,INST-70002,2022-02-17,2022-03-05,U1011,P203,LEAD-50002,Facebook,0434709a-95ff-4f5f-847f-352e292dc355,Repossession,607f30f7-b97f-4998-8692-3013917a49f7
3,ACC-90003,CUST-10003,Repossed,PAYG,2022-07-23,2024-01-03,INST-70003,2022-07-23,2022-07-27,U1008,P206,LEAD-50003,Facebook,0434709a-95ff-4f5f-847f-352e292dc355,Repossed,f24861a8-e367-48f3-b5a1-f264a8b80d4c
4,ACC-90004,CUST-10004,Refunded,PAYG,2023-12-13,2024-03-27,INST-70004,2023-12-13,2024-01-01,U1014,P205,LEAD-50004,Website,8530253e-a97b-4958-a303-88faaa4abee0,Refunded,f5abc6e7-d4ea-454d-a330-907652a0c601

In [307]:
def generateAccountSnapshots(group):
    group = group.sort_values('created_at')
    print("------------------------------ ")

    min_date = group['created_at'].min()
    account_age_days = (group['created_at'] - min_date).dt.days
    group['account_age_days'] = account_age_days
    group['is_currently_in_arrears'] = group['account_status'].apply(lambda x: True if x == 'Arrears' else False)

    return group

In [310]:
fact_accounts_snapshot_df = fact_accounts_snapshot_df.groupby("id").apply(generateAccountSnapshots)

------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------
------------------------------

C:\Users\tsuma.thomas\AppData\Local\Temp\ipykernel_36868\1917415358.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  fact_accounts_snapshot_df = fact_accounts_snapshot_df.groupby("id").apply(generateAccountSnapshots)

In [317]:
fact_accounts_snapshot_df = pd.merge(fact_accounts_snapshot_df, dim_customers_df.rename(columns={'id': 'customer_id'})[['customer_id', 'country_id']], left_on='customer_id', right_on='customer_id', how='left')

In [321]:
fact_accounts_snapshot_df

,id,customer_id,status,type,created_at,updated_at,Installation_id,Dispatch_date,First_installment_date,Agent_id,Proudct_id,lead_id,lead_source_name,lead_source_id,account_status,account_status_id,account_age_days,is_currently_in_arrears,country_id
0,ACC-90000,CUST-10000,Arrears,PAYG,2023-07-24,2024-02-22,INST-70000,2023-07-24,2023-08-10,U1008,P203,LEAD-50000,Roadshow,0f16ec51-002f-4044-8f19-18befbfbfa33,Arrears,1e277c75-34da-4859-8603-b0e16b0590e0,0,True,352d617d-673d-4173-9c03-051d840103e0
1,ACC-90001,CUST-10001,Complete,CASH,2023-07-30,2024-06-28,INST-70001,2023-07-30,2023-08-13,U1003,P206,LEAD-50001,Refer and Earn,d5fc05cb-b332-4898-905f-63a3840b4536,Complete,c7d10cc7-a0a1-4b48-afd4-1f3688b8e0aa,0,False,352d617d-673d-4173-9c03-051d840103e0
2,ACC-90002,CUST-10002,Repossession,PAYG,2022-02-17,2022-10-01,INST-70002,2022-02-17,2022-03-05,U1011,P203,LEAD-50002,Facebook,0434709a-95ff-4f5f-847f-352e292dc355,Repossession,607f30f7-b97f-4998-8692-3013917a49f7,0,False,b94de882-caef-44d8-b7f5-1cd7c293d491
3,ACC-90003,CUST-10003,Repossed,PAYG,2022-07-23,2024-01-03,INST-70003,2022-07-23,2022-07-27,U1008,P206,LEAD-50003,Facebook,0434709a-95ff-4f5f-847f-352e292dc355,Repossed,f24861a8-e367-48f3-b5a1-f264a8b80d4c,0,False,85bda175-cce8-43e0-a002-b0f799e0bac3
4,ACC-90004,CUST-10004,Refunded,PAYG,2023-12-13,2024-03-27,INST-70004,2023-12-13,2024-01-01,U1014,P205,LEAD-50004,Website,8530253e-a97b-4958-a303-88faaa4abee0,Refunded,f5abc6e7-d4ea-454d-a330-907652a0c601,0,False,85bda175-cce8-43e0-a002-b0f799e0bac3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,ACC-94495,CUST-14495,Complete,PAYG,2022-09-28,2023-03-29,INST-74495,2022-09-28,2022-10-01,U1011,P205,LEAD-54495,Walk-in,3417d4bf-677e-4ce0-9e02-56c3c10c5e2f,Complete,c7d10cc7-a0a1-4b48-afd4-1f3688b8e0aa,0,False,85bda175-cce8-43e0-a002-b0f799e0bac3
4496,ACC-94496,CUST-14496,No Deposit,CASH,2023-11-20,2024-01-19,INST-74496,2023-11-20,2023-11-30,U1011,P205,LEAD-54496,Roadshow,0f16ec51-002f-4044-8f19-18befbfbfa33,No Deposit,f772f358-b66e-4455-b077-80d1c301c4c5,0,False,85bda175-cce8-43e0-a002-b0f799e0bac3
4497,ACC-94497,CUST-14497,Arrears,PAYG,2023-04-16,2024-04-28,INST-74497,2023-04-16,2023-04-29,U1014,P207,LEAD-54497,Roadshow,0f16ec51-002f-4044-8f19-18befbfbfa33,Arrears,1e277c75-34da-4859-8603-b0e16b0590e0,0,True,352d617d-673d-4173-9c03-051d840103e0
4498,ACC-94498,CUST-14498,Advance,CASH,2022-08-29,2024-01-23,INST-74498,2022-08-29,2022-09-22,U1008,P204,LEAD-54498,Door to Door,3b82192a-856e-4535-a38a-2a5548d88f0c,Advance,a3311867-48d9-4e96-8733-380654a52595,0,False,352d617d-673d-4173-9c03-051d840103e0
4499,ACC-94499,CUST-14499,Refunded,CASH,2023-07-07,2023-10-09,INST-74499,2023-07-07,2023-07-15,U1017,P200,LEAD-54499,Facebook,0434709a-95ff-4f5f-847f-352e292dc355,Refunded,f5abc6e7-d4ea-454d-a330-907652a0c601,0,False,b94de882-caef-44d8-b7f5-1cd7c293d491

In [334]:
import uuid
for index, row in fact_accounts_snapshot_df.iterrows():
    print(row['country_id'])
    # break
    client.execute(
    """
        INSERT INTO sunculture_db.fact_accounts_snapshots
        (
            account_id,
            customer_id,
            product_id,
            country_id,
            account_status_id,
            lead_source_id,
            created_at,
            account_age_days,
            is_currently_in_arrears,
            payment_type,
            activation_date
        )
        VALUES
        """,
        [
            (
                str(row['id']),
                str(row['customer_id']),
                str(row['Proudct_id']),
                row['country_id'],
                row['account_status_id'],
                row['lead_source_id'],
                row['created_at'],
                row['account_age_days'],
                row['is_currently_in_arrears'],
                row['type'],
                row['First_installment_date']
            )
        ]
    )

352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
85bda175-cce8-43e0-a002-b0f799e0bac3
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
b94de882-caef-44d8-b7f5-1cd7c293d491
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
b94de882-caef-44d8-b7f5-1cd7c293d491
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
b94de882-caef-44d8-b7f5-1cd7c293d491
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
b94de882-caef-44d8-b7f5-1cd7c293d491
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
b94de882-caef-44d8-b7f5-1cd7c293d491
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
b94de882-caef-44d8-b7f5-1cd7c293d491
85bda175-cce8-43e0-a002-b0f799e0bac3
b94de882-caef-44d8-b7f5-1cd7c293d491
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
b94de882-caef-44d8-b7f5-1cd7c293d491
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
85bda175-cce8-43e0-a002-b0f799e0bac3
b94de882-caef-44d8-b7f5-1cd7c293d491
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
b94de882-caef-44d8-b7f5-1cd7c293d491
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
b94de882-caef-44d8-b7f5-1cd7c293d491
85bda175-cce8-43e0-a002-b0f799e0bac3
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
85bda175-cce8-43e0-a002-b0f799e0bac3
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
85bda175-cce8-43e0-a002-b0f799e0bac3
85bda175-cce8-43e0-a002-b0f799e0bac3
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
85bda175-cce8-43e0-a002-b0f799e0bac3
b94de882-caef-44d8-b7f5-1cd7c293d491
85bda175-cce8-43e0-a002-b0f799e0bac3
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
b94de882-caef-44d8-b7f5-1cd7c293d491
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
352d617d-673d-4173-9c03-051d840103e0
85bda175-cce8-43e0-a002-b0f799e0bac3

### Populate the fact_installations table:
fact_installations
(
    installation_id String,
    customer_id String,
    account_id String,
    product_id String,
    engineer_id String,
    country_id UUID,
    location_id UUID,
    sale_date Date,
    installation_date Date,
    installation_status String,
    created_at DateTime
)

In [363]:
fact_installations_df = installations.copy()
fact_installations_df = pd.merge(
    fact_installations_df.rename(columns={"Id": "installation_id"}), 
    accounts.rename(columns={"id":"account_id","Installation_id":"installation_id","status":"installation_status","Proudct_id":"product_id"})[['account_id','installation_id','customer_id','installation_status','product_id']],
    how="left",
    left_on='installation_id',
    right_on='installation_id'
)

In [364]:
fact_installations_df.head(2)

,installation_id,Installation_date,engineer_id,created_at,updated_at,account_id,customer_id,installation_status,product_id
0,INST-70000,2022-12-24,U1012,2022-12-24,2023-10-10,ACC-90000,CUST-10000,Arrears,P203
1,INST-70001,2022-01-08,U1026,2022-01-08,2024-02-27,ACC-90001,CUST-10001,Complete,P206

In [349]:
dim_customers_df = pd.DataFrame(client.execute("SELECT * FROM sunculture_db.dim_customer", with_column_types=True)[0], columns=[col[0] for col in client.execute("SELECT * FROM sunculture_db.dim_customer", with_column_types=True)[1]])
dim_customers_df.head()

,customer_id,gender,date_of_birth,age,age_bucket,created_at,latitude,longitude,location_id,country_id
0,CUST-14998,Male,1997-09-11,29,19-35,2022-09-24,2.105289,43.868141,ba7ad696-602c-4c55-9d83-0df79c5366a0,352d617d-673d-4173-9c03-051d840103e0
1,CUST-14999,Male,1988-07-03,38,36-50,2022-07-26,-4.316514,49.946022,450273c9-5f9f-419c-b90f-8b92bd1a4fcc,85bda175-cce8-43e0-a002-b0f799e0bac3
2,CUST-10000,Female,1983-10-22,43,36-50,2022-01-18,2.949384,42.616604,0c91ce94-e47a-4524-8c2e-99dd20bd4604,352d617d-673d-4173-9c03-051d840103e0
3,CUST-10001,Female,1978-05-25,48,36-50,2023-06-25,4.580776,46.412739,1be0d0fd-22b0-4598-9fa9-a08ba11f549c,352d617d-673d-4173-9c03-051d840103e0
4,CUST-10002,Male,1974-06-05,52,51+,2023-02-19,-1.344683,44.132175,f942620a-e675-4839-86c6-f3bbc9f42a3d,b94de882-caef-44d8-b7f5-1cd7c293d491

In [366]:
fact_installations_df = pd.merge(fact_installations_df, 
         dim_customers_df.rename(columns={'id': 'customer_id'})[['customer_id', 'country_id','location_id']], 
         left_on='customer_id', right_on='customer_id', how='left'
)

In [367]:
fact_sales_df = pd.DataFrame(client.execute("SELECT * FROM sunculture_db.fact_sales", with_column_types=True)[0], columns=[col[0] for col in client.execute("SELECT * FROM sunculture_db.fact_sales", with_column_types=True)[1]])
fact_sales_df.head()

,sale_id,customer_id,product_id,lead_source_id,agent_id,account_id,country_id,sale_date,sale_timestamp,account_type,account_status,created_at
0,SALE-104715,CUST-14715,P206,d5fc05cb-b332-4898-905f-63a3840b4536,U1011,ACC-94715,352d617d-673d-4173-9c03-051d840103e0,2023-09-05,1970-01-01,,,1970-01-01
1,SALE-102280,CUST-12280,P203,30f3c4db-628c-47d9-8a16-687a8962e0e1,U1016,ACC-92280,352d617d-673d-4173-9c03-051d840103e0,2022-09-01,1970-01-01,,,1970-01-01
2,SALE-102533,CUST-12533,P201,0f16ec51-002f-4044-8f19-18befbfbfa33,U1016,ACC-92533,352d617d-673d-4173-9c03-051d840103e0,2022-09-02,1970-01-01,,,1970-01-01
3,SALE-103325,CUST-13325,P205,0f16ec51-002f-4044-8f19-18befbfbfa33,U1011,ACC-93325,352d617d-673d-4173-9c03-051d840103e0,2022-09-03,1970-01-01,,,1970-01-01
4,SALE-102024,CUST-12024,P208,3b82192a-856e-4535-a38a-2a5548d88f0c,U1008,ACC-92024,352d617d-673d-4173-9c03-051d840103e0,2022-09-05,1970-01-01,,,1970-01-01

In [368]:
fact_installations_df.head(2)

,installation_id,Installation_date,engineer_id,created_at,updated_at,account_id,customer_id,installation_status,product_id,country_id,location_id
0,INST-70000,2022-12-24,U1012,2022-12-24,2023-10-10,ACC-90000,CUST-10000,Arrears,P203,352d617d-673d-4173-9c03-051d840103e0,0c91ce94-e47a-4524-8c2e-99dd20bd4604
1,INST-70001,2022-01-08,U1026,2022-01-08,2024-02-27,ACC-90001,CUST-10001,Complete,P206,352d617d-673d-4173-9c03-051d840103e0,1be0d0fd-22b0-4598-9fa9-a08ba11f549c

In [371]:
fact_installations_df = pd.merge(fact_installations_df, fact_sales_df[['account_id','sale_date']],on="account_id",how="left")

In [377]:
fact_installations_df['Installation_date'] = pd.to_datetime(fact_installations_df['Installation_date'], errors='coerce')
fact_installations_df['sale_date'] = pd.to_datetime(fact_installations_df['sale_date'], errors='coerce')
fact_installations_df['created_at'] = pd.to_datetime(fact_installations_df['created_at'], errors='coerce')

In [378]:
for index, row in fact_installations_df.iterrows():
    client.execute(
        """
        INSERT INTO sunculture_db.fact_installations
        (
            installation_id,
            account_id,
            customer_id,
            product_id,
            country_id,
            location_id,
            installation_status,
            sale_date,
            engineer_id,
            installation_date,
            created_at
        )
        VALUES
        """,
        [
            (
                str(row['installation_id']),
                str(row['account_id']),
                str(row['customer_id']),
                str(row['product_id']),
                row['country_id'],
                row['location_id'],
                row['installation_status'],
                row['sale_date'],
                str(row['engineer_id']),
                row['Installation_date'],
                row['created_at']
            )
        ]
    )

### Populate the fact_leads_funnel table

fact_lead_funnel
(
    lead_id String,
    customer_id String,
    lead_source_id UInt32,
    agent_id String,
    country_id UInt32,
    lead_created_date Date,
    converted_to_account UInt8,
    converted_to_sale UInt8,
    converted_to_installation UInt8,
    days_to_account Nullable(UInt32),
    days_to_sale Nullable(UInt32),
    days_to_dispatch Nullable(UInt32),
    lead_quality_score Float32,
    created_at DateTime
)

In [14]:
facts_leads_funnel_df = leads.copy()
facts_leads_funnel_df = facts_leads_funnel_df.rename(columns={'Id': "lead_id"})
dim_leads_source = pd.DataFrame(client.execute("SELECT * FROM sunculture_db.dim_lead_source", with_column_types=True)[0], columns=[col[0] for col in client.execute("SELECT * FROM sunculture_db.dim_lead_source", with_column_types=True)[1]])
print(facts_leads_funnel_df.describe())
print(dim_leads_source.columns)
facts_leads_funnel_df = pd.merge(facts_leads_funnel_df.rename(columns={'Source': 'lead_source_name'}), dim_leads_source, left_on='lead_source_name', right_on='lead_source_name', how='left')
account_sales_merged = pd.merge(accounts.rename(columns={'id': 'account_id','created_at':'account_created_at','Dispatch_date':'dispatch_date','Agent_id':'agent_id'})[['account_id','lead_id','Installation_id','account_created_at','dispatch_date','agent_id']], sales.rename(columns={"Sale_date":"sale_date", 'Id':"sale_id"})[['sale_id','sale_date','account_id']], left_on='account_id', right_on='account_id', how='left')
print(account_sales_merged.describe())
facts_leads_funnel_df = pd.merge(facts_leads_funnel_df, account_sales_merged, left_on='lead_id', right_on='lead_id', how='left')

           lead_id    Source customer_id  created_at  updated_at
count         6000      6000        5000        6000        6000
unique        6000         8        5000         821         792
top     LEAD-50000  Roadshow  CUST-10000  2022-03-10  2024-04-21
freq             1       796           1          17          27
Index(['lead_source_id', 'lead_source_name'], dtype='object')
       account_id     lead_id Installation_id account_created_at  \
count        4750        4750            4500               4750
unique       4750        4750            4500                730
top     ACC-90000  LEAD-50000      INST-70000         2023-07-16
freq            1           1               1                 16

       dispatch_date agent_id      sale_id   sale_date
count           4750     4750         4750        4750
unique           730        6         4750         730
top       2023-07-16    U1017  SALE-100000  2023-07-16
freq              16      862            1          16

In [15]:
facts_leads_funnel_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   lead_id             6000 non-null   object
 1   lead_source_name    6000 non-null   object
 2   customer_id         5000 non-null   object
 3   created_at          6000 non-null   object
 4   updated_at          6000 non-null   object
 5   lead_source_id      6000 non-null   object
 6   account_id          4750 non-null   object
 7   Installation_id     4500 non-null   object
 8   account_created_at  4750 non-null   object
 9   dispatch_date       4750 non-null   object
 10  agent_id            4750 non-null   object
 11  sale_id             4750 non-null   object
 12  sale_date           4750 non-null   object
dtypes: object(13)
memory usage: 609.5+ KB

In [16]:
facts_leads_funnel_df['converted_to_account'] = facts_leads_funnel_df['lead_id'].isin(accounts['lead_id'])

In [17]:
facts_leads_funnel_df['converted_to_sale'] = facts_leads_funnel_df['sale_id'].apply(lambda x: True if pd.notnull(x) else False)

In [18]:
facts_leads_funnel_df['converted_to_installation'] = facts_leads_funnel_df['Installation_id'].apply(lambda x: True if pd.notnull(x) else False)

In [19]:
facts_leads_funnel_df['account_created_at'] = pd.to_datetime(facts_leads_funnel_df['account_created_at'], errors='coerce')
facts_leads_funnel_df['created_at'] = pd.to_datetime(facts_leads_funnel_df['created_at'], errors='coerce')
facts_leads_funnel_df['days_to_account'] = (facts_leads_funnel_df['account_created_at'] - facts_leads_funnel_df['created_at']).dt.days

In [20]:
facts_leads_funnel_df['sale_date'] = pd.to_datetime(facts_leads_funnel_df['sale_date'], errors='coerce')
facts_leads_funnel_df['days_to_sale'] = (facts_leads_funnel_df['sale_date'] - facts_leads_funnel_df['created_at']).dt.days

In [21]:
facts_leads_funnel_df['dispatch_date'] = pd.to_datetime(facts_leads_funnel_df['dispatch_date'], errors='coerce')
facts_leads_funnel_df['days_to_dispatch'] = (facts_leads_funnel_df['dispatch_date'] - facts_leads_funnel_df['created_at']).dt.days

In [24]:
facts_leads_funnel_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 19 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   lead_id                    6000 non-null   object
 1   lead_source_name           6000 non-null   object
 2   customer_id                5000 non-null   object
 3   created_at                 6000 non-null   datetime64[ns]
 4   updated_at                 6000 non-null   object
 5   lead_source_id             6000 non-null   object
 6   account_id                 4750 non-null   object
 7   Installation_id            4500 non-null   object
 8   account_created_at         4750 non-null   datetime64[ns]
 9   dispatch_date              4750 non-null   datetime64[ns]
 10  agent_id                   4750 non-null   object
 11  sale_id                    4750 non-null   object
 12  sale_date                  4750 non-null   datetime64[ns]
 13  converted_to_account       6000 non-null   bool
 14  converted_to_sale          6000 non-null   bool
 15  converted_to_installation  6000 non-null   bool
 16  days_to_account            4750 non-null   float64
 17  days_to_sale               4750 non-null   float64
 18  days_to_dispatch           4750 non-null   float64
dtypes: bool(3), datetime64[ns](4), float64(3), object(9)
memory usage: 767.7+ KB

In [26]:
facts_leads_funnel_df.converted_to_account.value_counts()

converted_to_account
True     4750
False    1250
Name: count, dtype: int64

In [27]:
accounts.loc[~(accounts['id'].isin(sales['account_id']))]

Empty DataFrame
Columns: [id, customer_id, status, type, created_at, updated_at, Installation_id, Dispatch_date, First_installment_date, Agent_id, Proudct_id, lead_id]
Index: []

In [28]:
facts_leads_funnel_df.columns

Index(['lead_id', 'lead_source_name', 'customer_id', 'created_at',
       'updated_at', 'lead_source_id', 'account_id', 'Installation_id',
       'account_created_at', 'dispatch_date', 'agent_id', 'sale_id',
       'sale_date', 'converted_to_account', 'converted_to_sale',
       'converted_to_installation', 'days_to_account', 'days_to_sale',
       'days_to_dispatch'],
      dtype='object')

In [29]:
facts_leads_funnel_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 19 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   lead_id                    6000 non-null   object
 1   lead_source_name           6000 non-null   object
 2   customer_id                5000 non-null   object
 3   created_at                 6000 non-null   datetime64[ns]
 4   updated_at                 6000 non-null   object
 5   lead_source_id             6000 non-null   object
 6   account_id                 4750 non-null   object
 7   Installation_id            4500 non-null   object
 8   account_created_at         4750 non-null   datetime64[ns]
 9   dispatch_date              4750 non-null   datetime64[ns]
 10  agent_id                   4750 non-null   object
 11  sale_id                    4750 non-null   object
 12  sale_date                  4750 non-null   datetime64[ns]
 13  converted_to_account       6000 non-null   bool
 14  converted_to_sale          6000 non-null   bool
 15  converted_to_installation  6000 non-null   bool
 16  days_to_account            4750 non-null   float64
 17  days_to_sale               4750 non-null   float64
 18  days_to_dispatch           4750 non-null   float64
dtypes: bool(3), datetime64[ns](4), float64(3), object(9)
memory usage: 767.7+ KB

In [30]:
facts_leads_funnel_df['days_to_account'] = facts_leads_funnel_df['days_to_account'].fillna(-1).astype(int)
facts_leads_funnel_df['days_to_sale'] = facts_leads_funnel_df['days_to_sale'].fillna(-1).astype(int)
facts_leads_funnel_df['days_to_dispatch'] = facts_leads_funnel_df['days_to_dispatch'].fillna(-1).astype(int)

In [31]:
facts_leads_funnel_df['days_to_account'] = facts_leads_funnel_df['days_to_account'].apply(lambda x: x if x >= 0 else 99999)
facts_leads_funnel_df['days_to_sale'] = facts_leads_funnel_df['days_to_sale'].apply(lambda x: x if x >= 0 else 99999)
facts_leads_funnel_df['days_to_dispatch'] = facts_leads_funnel_df['days_to_dispatch'].apply(lambda x: x if x >= 0 else 99999)

In [ ]:
string_cols = ['lead_id', 'agent_id', 'customer_id']
for col in string_cols:
    facts_leads_funnel_df[col] = facts_leads_funnel_df[col].fillna('').astype(str)

days_cols = ['days_to_account', 'days_to_sale', 'days_to_dispatch']
for col in days_cols:
    facts_leads_funnel_df[col] = facts_leads_funnel_df[col].replace(99999, None)

bool_cols = ['converted_to_account', 'converted_to_sale', 'converted_to_installation']
for col in bool_cols:
    facts_leads_funnel_df[col] = facts_leads_funnel_df[col].astype(int)

In [39]:
from uuid import UUID

# ── Clean dataframe first ─────────────────────────────────────────────────────
string_cols = ['lead_id', 'customer_id', 'agent_id']
for col in string_cols:
    facts_leads_funnel_df[col] = facts_leads_funnel_df[col].fillna('').astype(str)

# UUID column — must stay as string in correct UUID format
facts_leads_funnel_df['lead_source_id'] = facts_leads_funnel_df['lead_source_id'].astype(str)

# Boolean → int
bool_cols = ['converted_to_account', 'converted_to_sale', 'converted_to_installation']
for col in bool_cols:
    facts_leads_funnel_df[col] = facts_leads_funnel_df[col].astype(int)

# Days sentinel → None
days_cols = ['days_to_account', 'days_to_sale', 'days_to_dispatch']
for col in days_cols:
    facts_leads_funnel_df[col] = facts_leads_funnel_df[col].replace(99999, None)
    facts_leads_funnel_df[col] = facts_leads_funnel_df[col].where(
        facts_leads_funnel_df[col].notna(), None
    )

# ── Build records ─────────────────────────────────────────────────────────────
records = []
for _, row in facts_leads_funnel_df.iterrows():
    # Validate UUID format before inserting
    try:
        uuid_val = str(UUID(str(row['lead_source_id'])))
    except (ValueError, AttributeError):
        print(f"Skipping row with bad lead_source_id: {row['lead_source_id']}")
        continue

    records.append((
        str(row['lead_id']),
        str(row['customer_id']),
        uuid_val,                                    # validated UUID string
        str(row['agent_id']) if row['agent_id'] else None,
        row['created_at'],
        int(row['converted_to_account']),
        int(row['converted_to_sale']),
        int(row['converted_to_installation']),
        row['days_to_account'],                      # None or int
        row['days_to_sale'],
        row['days_to_dispatch'],
        float(row.get('lead_quality_score', 0.0)),
        # created_at has DEFAULT now() so omit it
    ))

print(f"Records to insert: {len(records)}")

# ── Bulk insert ───────────────────────────────────────────────────────────────
client.execute(
    """
    INSERT INTO sunculture_db.fact_lead_funnel
    (lead_id, customer_id, lead_source_id, agent_id, lead_created_date,
     converted_to_account, converted_to_sale, converted_to_installation,
     days_to_account, days_to_sale, days_to_dispatch, lead_quality_score)
    VALUES
    """,
    records
)
print(f"✓ Inserted {len(records)} rows successfully")

Records to insert: 6000
✓ Inserted 6000 rows successfully

In [507]:
facts_leads_funnel_df['days_to_account'].describe()

count    4500.00000
mean      -45.10600
std       320.64538
min      -817.00000
25%      -271.25000
50%       -54.00000
75%       192.00000
max       699.00000
Name: days_to_account, dtype: float64

0       101.0
1       133.0
2      -130.0
3       114.0
4        23.0
        ...
5995      NaN
5996      NaN
5997      NaN
5998      NaN
5999      NaN
Name: days_to_account, Length: 6000, dtype: float64